/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.

import { VoterForm } from "@/components/VoterForm";

export default function HomePage() {
  return (
    <main className="flex-grow flex flex-col items-center justify-center p-4 sm:p-8 bg-gradient-to-br from-background to-secondary">
      <VoterForm />
    </main>
  );
}

import type {Metadata} from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { AnimatedLogoBackground } from '@/components/AnimatedLogoBackground';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'BallotBox',
  description: 'School Election Ballot App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        {/* Font links are handled by next/font */}
      </head>
      <body className={`font-body antialiased min-h-screen flex flex-col`} suppressHydrationWarning={true}>
        <AnimatedLogoBackground />
        <div className="relative z-0 flex flex-col flex-1"> {/* Ensures content is above background and takes space */}
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
